server:
  port: 8083
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 使用阿里的Druid连接池
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 填写你数据库的url、登录名、密码和数据库名
    url: jdbc:mysql://192.168.36.131:3306/springboot_kang?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    druid:
      # 连接池的配置信息
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录 http://localhost:8083/druid/sql.html
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  
  #缓存配置  
  cache:
    type: REDIS
    redis:
      cache-null-values: false
      time-to-live: 600000ms
      use-key-prefix: true
  
  #redis配置  
  redis:
    host: 192.168.36.131
    port: 6379
    #password: 
    timeout: 36000ms # 连接超时时间（毫秒）
    database: 0
    lettuce: 
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8  # 连接池中的最大空闲连接 默认 8
        min-idle: 0  # 连接池中的最小空闲连接 默认 0
  
  #mongodb配置      
  data:
    mongodb:
      database: admin
      authentication-database: userAdminAnyDatabase
      uri: mongodb://admin:123456@192.168.36.131:27017
  
  #rabbitmq配置
  rabbitmq:
    host: 192.168.36.131
    port: 5672
    username: admin
    password: mypass
    virtual-host: /
    publisher-confirms: true   #开启发送确认
    publisher-returns: true  #开启发送失败回退
    #开启ack
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual #采取手动应答
        #concurrency: 1 # 指定最小的消费者数量
        #max-concurrency: 1 #指定最大的消费者数量
        retry:
          enabled: true # 是否支持重试
  
        
#Mybatis配置
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.kang.model.mybatis
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

# log
logging:
  level:
    root: com.kang.mapper:INFO
    
#FastDFS配置
fdfs:
  webserver: http://192.168.36.131:8080/
  soTimeout: 1501
  connectTimeout: 601
  thumbImage:     #缩略图生成参数
    width: 150
    height: 150
  trackerList:            #TrackerList参数,支持多个
    - 192.168.36.131:22122

#shiro配置    
shiro: 
  #unauthorizedUrl: /test/unauthorizedurl
  loginUrl: /unauthorizedurl
  #successUrl: /test/login
  web: 
    enabled: true

#线程池的配置
threadpool:
  core-pool-size: 10
  max-pool-size: 20
  queue-capacity: 1000
  keep-alive-seconds: 600
   
